<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
	</PropertyGroup>

	<PropertyGroup Condition=" '$(RunConfiguration)' == 'Security' " />
	<ItemGroup>
		<PackageReference Include="cCoder.CodeAnalysis" Version="2026.8.26.1209" PrivateAssets="all" />
		<PackageReference Include="cCoder.Data" Version="2026.8.12.1324" />
		<PackageReference Include="Microsoft.AspNetCore.OData" Version="9.5.0" />
		<PackageReference Include="Microsoft.OpenApi" Version="3.10.2" />
    <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="10.2.3" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="10.2.3" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.2.3" />

	</ItemGroup>

	<ItemGroup>
	  <None Remove="Microsoft.EntityFrameworkCore.Design" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\cCoder.Security\cCoder.Security.csproj" />
    <ProjectReference Include="..\..\cCoder.Security.Data\cCoder.Security.Data.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Content Update="appsettings.json">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>
</Project>
